---

port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments

### content configuration ###
title:       "CU CS VM"
keywords:    "Colorado, Virtual Machine, VM, CU CS VM, CU, CU CS"
description: "CU CS Virtual Machine Info"
source_link: "https://github.com/asayler/cu-cs-vm-site"
favicon:     "img/favicon.ico"
touch_icon:  "img/touch.png"
google_analytics_key: "UA-38165152-2"
baseurl: "/vm/"
url: "https://foundation.cs.colorado.edu"

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#44D613'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#00C0C0'
